import React, { createContext, useContext, useEffect, useState } from "react";

const dict = {
  fi: {
    appName: "TSV Palaute",
    appTagline: "Työsuojelupalaute · Varasto & Logistiikka",
    submitFeedback: "Lähetä palaute",
    adminLogin: "Ylläpitäjän kirjautuminen",
    language: "Kieli",
    theme: "Teema",
    light: "Vaalea",
    dark: "Tumma",
    logout: "Kirjaudu ulos",

    // Form
    formTitle: "Anna palautetta turvallisesti",
    formSubtitle: "Palautteesi auttaa työsuojeluvaltuutettua parantamaan työoloja. Voit pysyä halutessasi anonyyminä.",
    nameOptional: "Nimi (valinnainen)",
    namePlaceholder: "Etunimi tai koko nimi",
    stayAnonymous: "Pysy anonyyminä",
    anonymousNote: "Lähetät palautetta nimettömänä. Henkilöllisyytesi ei tallennu.",
    shift: "Vuoro",
    morning: "Aamuvuoro",
    evening: "Iltavuoro",
    night: "Yövuoro",
    category: "Kategoria",
    safety: "Turvallisuus",
    workload: "Työkuorma",
    equipment: "Laitteet",
    environment: "Työympäristö",
    organization: "Organisointi / Viestintä",
    other: "Muu",
    severity: "Vakavuus",
    low: "Matala",
    medium: "Keskitaso",
    high: "Korkea",
    comment: "Kommentit ja havainnot",
    commentPlaceholder: "Kuvaile tilannetta, ajankohtaa, paikkaa tai parannusehdotuksia...",
    contactRequested: "Haluan, että minuun otetaan yhteyttä tästä palautteesta",
    submit: "Lähetä palaute",
    submitting: "Lähetetään...",
    successTitle: "Kiitos palautteestasi!",
    successBody: "Palautteesi on tallennettu turvallisesti. Vain työsuojeluvaltuutettu näkee sen.",
    sendAnother: "Lähetä toinen palaute",
    categoriesIntro: "Valitse kategoriat joista haluat antaa palautetta. Voit vastata yhteen tai useampaan.",
    addAnswer: "Lisää vastaus",
    removeAnswer: "Poista vastaus",
    answered: "Vastattu",
    skip: "Ohita",
    minOneCategory: "Vastaa vähintään yhteen kategoriaan",
    submittedCount: "palaute(tta) lähetetty",
    expandCategory: "Avaa",
    collapseCategory: "Sulje",

    // Login
    loginTitle: "Ylläpitäjän kirjautuminen",
    loginSubtitle: "Vain TSV-edustajille",
    email: "Sähköposti",
    password: "Salasana",
    signIn: "Kirjaudu sisään",
    signingIn: "Kirjaudutaan...",
    backToForm: "Takaisin palautelomakkeeseen",
    invalidCreds: "Virheellinen sähköposti tai salasana",

    // Dashboard
    dashboard: "Hallintapaneeli",
    overview: "Yleiskatsaus",
    totalReports: "Palautteita yhteensä",
    unreviewed: "Käsittelemättömät",
    contactRequests: "Yhteydenottopyynnöt",
    highSeverity: "Korkea vakavuus",
    byCategory: "Kategorioittain",
    byShift: "Vuoroittain",
    bySeverity: "Vakavuuden mukaan",
    trend14: "Trendi (14 päivää)",
    filters: "Suodattimet",
    allShifts: "Kaikki vuorot",
    allCategories: "Kaikki kategoriat",
    allSeverities: "Kaikki vakavuudet",
    onlyUnreviewed: "Vain käsittelemättömät",
    search: "Hae kommenteista...",
    dateFrom: "Alkaen",
    dateTo: "Asti",
    clearFilters: "Tyhjennä",
    exportPdf: "Vie PDF",
    exportCsv: "Vie CSV",
    reports: "Palautteet",
    anonymous: "Anonyymi",
    markReviewed: "Merkitse käsitellyksi",
    markUnreviewed: "Merkitse käsittelemättömäksi",
    reviewed: "Käsitelty",
    contactWanted: "Yhteydenotto pyydetty",
    deleteConfirm: "Poistetaanko tämä palaute pysyvästi?",
    delete: "Poista",
    noReports: "Ei palautteita näillä suodattimilla.",
    submitted: "Lähetetty",
  },
  en: {
    appName: "TSV Feedback",
    appTagline: "Workplace Safety Feedback · Warehouse & Logistics",
    submitFeedback: "Submit feedback",
    adminLogin: "Admin login",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    logout: "Log out",

    formTitle: "Share feedback safely",
    formSubtitle: "Your feedback helps the safety representative improve working conditions. You can stay anonymous if you wish.",
    nameOptional: "Name (optional)",
    namePlaceholder: "First name or full name",
    stayAnonymous: "Stay anonymous",
    anonymousNote: "You're submitting anonymously. Your identity will not be stored.",
    shift: "Shift",
    morning: "Morning",
    evening: "Evening",
    night: "Night",
    category: "Category",
    safety: "Safety",
    workload: "Workload",
    equipment: "Equipment",
    environment: "Work environment",
    organization: "Organization / Communication",
    other: "Other",
    severity: "Severity",
    low: "Low",
    medium: "Medium",
    high: "High",
    comment: "Comments and observations",
    commentPlaceholder: "Describe the situation, time, location or improvement suggestions...",
    contactRequested: "I would like to be contacted about this feedback",
    submit: "Submit feedback",
    submitting: "Submitting...",
    successTitle: "Thank you for your feedback!",
    successBody: "Your feedback has been stored securely. Only the safety representative can see it.",
    sendAnother: "Send another report",

    loginTitle: "Admin login",
    loginSubtitle: "Restricted to TSV representatives",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in...",
    backToForm: "Back to feedback form",
    invalidCreds: "Invalid email or password",

    dashboard: "Dashboard",
    overview: "Overview",
    totalReports: "Total reports",
    unreviewed: "Unreviewed",
    contactRequests: "Contact requests",
    highSeverity: "High severity",
    byCategory: "By category",
    byShift: "By shift",
    bySeverity: "By severity",
    trend14: "Trend (14 days)",
    filters: "Filters",
    allShifts: "All shifts",
    allCategories: "All categories",
    allSeverities: "All severities",
    onlyUnreviewed: "Only unreviewed",
    search: "Search comments...",
    dateFrom: "From",
    dateTo: "To",
    clearFilters: "Clear",
    exportPdf: "Export PDF",
    exportCsv: "Export CSV",
    reports: "Reports",
    anonymous: "Anonymous",
    markReviewed: "Mark reviewed",
    markUnreviewed: "Mark unreviewed",
    reviewed: "Reviewed",
    contactWanted: "Contact requested",
    deleteConfirm: "Permanently delete this feedback?",
    delete: "Delete",
    noReports: "No feedback matches these filters.",
    submitted: "Submitted",
  },
};

const LangCtx = createContext(null);

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem("tsv_lang") || "fi");
  useEffect(() => localStorage.setItem("tsv_lang", lang), [lang]);
  const t = (key) => dict[lang][key] ?? key;
  return <LangCtx.Provider value={{ lang, setLang, t }}>{children}</LangCtx.Provider>;
};

export const useLang = () => useContext(LangCtx);
